lighthousecollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
path('', views.home, name='home'),
path('about/', views.about, name='about'),
path('lighthouses/', views.lighthouses_index, name='index'),
path('lighthouses/<int:lighthouse_id>/', views.lighthouses_detail, name='detail'),
path('lighthouses/create/', views.LighthouseCreate.as_view(), name='lighthouses_create'),
path('lighthouses/<int:pk>/update/', views.LighthouseUpdate.as_view(), name='lighthouses_update'),
path('lighthouses/<int:pk>/delete/', views.LighthouseDelete.as_view(), name='lighthouses_delete'),
path('lighthouses/<int:lighthouse_id>/add_visitor/', views.add_visitor, name='add_visitor'),
]

main_app/models.py
from django.db import models
from django.urls import reverse

SESSIONS = (
    ('M', 'Morning'),
    ('A', 'Afternoon'),
    ('E', 'Evening')
)

class Lighthouse(models.Model):
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    height = models.IntegerField()
    built = models.IntegerField()
    description = models.TextField(max_length=250)

    def __str__(self):
        return f'{self.name} ({self.id})'

    def get_absolute_url(self):
        return reverse('detail', kwargs={'lighthouse_id': self.id})

class Visitor(models.Model):
    date = models.DateField('visiting date')
    session = models.CharField(
        max_length=1,
        choices=SESSIONS,
        default=SESSIONS[0][0]
    )

    lighthouse = models.ForeignKey(Lighthouse, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_session_display()} on {self.date}"

    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Visitor

class VisitorForm(ModelForm):
    class Meta:
        model = Visitor
        fields = ['date', 'session']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
# Import the Lighthouse Model
from .models import Lighthouse
from .forms import VisitorForm


# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def lighthouses_index(request):
    lighthouses = Lighthouse.objects.all() # Retrive all lighthouses
    return render(request, 'lighthouses/index.html', 
    {
        'lighthouses': lighthouses
    }
)

def lighthouses_detail(request, lighthouse_id): 
    # need the lighthouse_id parameter because of lighthouse/<int:lighthouse_id> in urls.py
    lighthouse = Lighthouse.objects.get(id=lighthouse_id)
    visitor_form = VisitorForm()
    return render(request, 'lighthouses/detail.html', { 
        'lighthouse': lighthouse, 'visitor_form': visitor_form 
    })

def add_visitor(request, lighthouse_id):
    form = VisitorForm(request.POST)
    if form.is_valid():
        new_visitor = form.save(commit=False)
        new_visitor.lighthouse_id = lighthouse_id
        new_visitor.save()
    return redirect('detail', lighthouse_id=lighthouse_id)

class LighthouseCreate(CreateView):
    model = Lighthouse
    fields = '__all__'

class LighthouseUpdate(UpdateView):
    model = Lighthouse
    fields = ['location', 'built', 'description']

class LighthouseDelete(DeleteView):
    model = Lighthouse
    success_url = '/lighthouses'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

    <h1>About the LightHouse Collector</h1>
    <hr>
    <p>Hire the Lighthouse Collector!</p>
    <footer>All Rights Reserved, &copy; 2022 Lighthouse Collector</footer>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Lighthouse Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;Lighthouse Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'lighthouses_create' %}">Add a Lighthouse</a></li>
          <li><a href="{% url 'index' %}">All Lighthouses</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2021 Cat Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}

{% block content %}

<h1>Welcome to Lighthouse Collector!</h1>

{% endblock %}

main_app/templates/lighthouses/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Lighthouse Details</h1>

<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ lighthouse.name }}</span>
                <p>Location: {{ lighthouse.location }}</p>
                <p>Height: {{ lighthouse.height }}m</p>
                <p>Built: {{ lighthouse.built }}</p>
                <p>Description: {{ lighthouse.description|linebreaks }}</p>
            </div>
            <div class="card-action">
                <a href="{% url 'lighthouses_update' lighthouse.id %}">Edit</a>
                <a href="{% url 'lighthouses_delete' lighthouse.id %}">Delete</a>
            </div>
        </div>
    </div>
    <div class="col s6">
        <form action="{% url 'add_visitor' lighthouse.id %}" method="POST">
            {% csrf_token %}
            {{ visitor_form.as_p }}
            <input type="submit" class="btn" value="Add Visitor">
        </form>
        <table class="striped">
            <thead>
                <tr><th>Date</th><th>Session</th></tr>
            </thead>
            <tbody>
                {% for visitor in lighthouse.visitor_set.all %}
                    <tr>
                        <td>{{visitor.date}}</td>
                        <td>{{visitor.get_session_display}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<script>
    const dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
      format: 'yyyy-mm-dd',
      defaultDate: new Date(),
      setDefaultDate: true,
      autoClose: true
    });

    const selectEl = document.getElementById('id_session');
    M.FormSelect.init(selectEl);
  </script>
{% endblock %}

main_app/templates/lighthouses/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Lighthouse List</h1>

{% for lighthouse in lighthouses %}
    <div class="card">
        <a href="{% url 'detail' lighthouse.id %}">
            <div class="card-content">
                <span class="card-title">{{ lighthouse.name }}</span>
                <p>Location: {{ lighthouse.location }}</p>
                <p>Built: {{ lighthouse.built }}</p>
                <p>Height: {{ lighthouse.height }}m</p>
            </div>
        </a>
    </div>
{% endfor %}

{% endblock %}

main_app/templates/main_app/lighthouse_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

    <h1>Delete Lighthouse</h1>

    <h4>Are you sure you want to delete <span class="teal-text">{{object.name}}</span>?</h4>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes - Delete!" class="btn">
        <a href="{% url 'detail' lighthouse.id %}">Cancel</a>
    </form>

{% endblock %}

main_app/templates/main_app/lighthouse_form.html
{% extends 'base.html' %}

{% block content %}

    {% if object %}
        <h1>Edit <span class="teal-text">{{ object.name }}</span></h1>
    {% else %}
        <h1>Add Lighthouse</h1>
    {% endif %}
    <!-- Leaving the action empty makes the form post to the same url used to display it -->
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{ form }}
        </table>
        <input type="submit" name="Submit!" class="btn">
    </form>

{% endblock %}